//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.Entites
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class Services
    {
        [JsonPropertyName("IdServices")]
        public string Id { get; set; }

        [JsonPropertyName("NameServices")]
        public string ServiceName { get; set; }

        [JsonPropertyName("TypeOfService")]
        public string ServiceType { get; set; }

        [JsonPropertyName("CodeService")]
        public string ServiceCode { get; set; }

        [JsonPropertyName("Cost")]
        public string ServicePrice { get; set; }
    }
}
